[SERVICE]
    Flush         5
    Log_Level     info

[INPUT]
    Name          cpu
    Tag           cpu.logs
    Interval_Sec  5

[OUTPUT]
    Name                         s3
    Match                        cpu.*
    bucket                       apps-logs-dev
    region                       us-west-1
    role_arn                     ${LOG_WRITER_ROLE_ARN}
    total_file_size              10M
    upload_timeout               60s
    s3_key_format                /cpu-logs/$TAG/%Y/%m/%d/%H/%M/%S
    use_put_object               On
