input {
  s3 {
    bucket        => "apps-logs-dev"
    region        => "us-west-1"
    prefix        => "cpu-logs/"
    role_arn      => "${LOG_READER_ROLE_ARN}"
    interval      => 60
    sincedb_path  => "/var/lib/logstash/sincedb_s3"
    codec         => "json"
  }
}

filter {
  date {
    match => ["date", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    add_field => { "source" => "s3-cpu-logs" }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST:=http://localhost:9200}"]
    index => "cpu-logs-%{+YYYY.MM.dd}"
  }
}
